var litext = [];
litext[0]="<li><a href='javascript:goSunny(\""+adLink1+"\", \""+adRtn1+"\")'>"+adText1+"<img style='display:none;' src='"+Logpath+"?set=ad_counter&viewcount="+adNum1+"'></li>";
litext[1]="<li><a href='javascript:goSunny(\""+adLink2+"\", \""+adRtn2+"\")'>"+adText2+"<img style='display:none;' src='"+Logpath+"?set=ad_counter&viewcount="+adNum2+"'></li>";
litext[2]="<li><a href='javascript:goSunny(\""+adLink3+"\", \""+adRtn3+"\")'>"+adText3+"<img style='display:none;' src='"+Logpath+"?set=ad_counter&viewcount="+adNum3+"'></li>";
litext[3]="<li><a href='javascript:goSunny(\""+adLink4+"\", \""+adRtn4+"\")'>"+adText4+"<img style='display:none;' src='"+Logpath+"?set=ad_counter&viewcount="+adNum4+"'></li>";
litext[4]="<li><a href='javascript:goSunny(\""+adLink5+"\", \""+adRtn5+"\")'>"+adText5+"<img style='display:none;' src='"+Logpath+"?set=ad_counter&viewcount="+adNum5+"'></li>";
litext[5]="<li><a href='javascript:goSunny(\""+adLink6+"\", \""+adRtn6+"\")'>"+adText6+"<img style='display:none;' src='"+Logpath+"?set=ad_counter&viewcount="+adNum6+"'></li>";
